### ISSUE TITLE
情绪 | 友台

### ISSUE THREAD

**Issue by hi-franksun** [hi-franksun/hi-franksun.github.io#10]
https://sunyunxian.github.io/post/wo-de-qing-xu/

**Comment by youtai2020** [comment]
今晚早点睡觉，明天回南京，结束昼夜颠倒的一个月，准备一周，开始找工作。

**Comment by youtai2020** [comment]
好好调整自己，好好的生活！

**Comment by youtai2020** [comment]
日谈公园这期「[止庵：太宰治是给世界兜底的一个人](http://music.163.com/dj?id=2067674186&userid=517967468)」很棒，低下的评论也很棒，一些话题都值得反思。

**Comment by youtai2020** [comment]
今日南京之行：
1. 和发小、表弟和表妹三个人在南航后街的烤肉店吃饭，很棒，就是这家店不咋样；
2. 吃完饭本来打算去找小红聊天，发现时间不够了，跑到鼓楼转了一圈，天气真的太好了，南京话真的太亲切了！
3. 跑了几家鸭子店，有一家烤鸭卖完了，选了两家各斩半只，带回上海吃。
4. 还蛮迷茫的，说出来的感受，也许努力拼搏就是为了能在南京有个家，可是然后呢？
5. 我应该是个渣男了，看到漂亮女孩子会多看人家好几眼，还喜欢看人家的腿...

![image](https://user-images.githubusercontent.com/42464504/95675236-43a2e800-0be8-11eb-8768-f0496cc8a26e.jpeg)

![image](https://user-images.githubusercontent.com/42464504/95675324-fbd09080-0be8-11eb-8237-194d10a610e3.jpeg)

**Comment by youtai2020** [comment]
每次看别人博客都有被激励到，向他们学习，我比他们年纪大很多，认知上却差很多，要努力鸭！

**Comment by youtai2020** [comment]
我今天所有的情绪和感受，都是过去时间的所作所为的一种反应。

**Comment by youtai2020** [comment]
一定要有长远的眼光，往前看，站在整个生命长度的角度上，看现在的一切，以及决定要做的事情，就不会陷入死胡同，很倔强的那种状态，一定要看远点。

**Comment by youtai2020** [comment]
Famliy is not an import thing, it's everything.

**Comment by youtai2020** [comment]
Today, give yourself a break!

**Comment by youtai2020** [comment]
获取信息的选择：
1. 经典书，专业书；
2. 一些有趣的观点和放松的内容，目前推荐：blog、twitter；
3. 不要看单篇文章，包括公众号、知乎等没有任何东西的内容；

**Comment by youtai2020** [comment]
今天开始正式戒烟！

**Comment by youtai2020** [comment]
Durov's 在他的 Telegram Channel 分享了自己 36 岁保持年轻的几个方法：

> 以下是原文

As I’m turning 36, some people ask how I manage to look younger than my age. I’ve asked the same question of many people who age well (from Jared Leto to a random fitness trainer who looks like 25 at 50). Here’s what all of these young-looking individuals do (and don’t):

1. AVOID alcohol. There may be some rare exceptions, but in general, alcohol (as well as other addictive substances) makes people less healthy and visually older.

2. Sleep a LOT. Sleep is when your body repairs itself. You can’t borrow it: lack of sleep during the week can’t be compensated with oversleeping on the weekend.

3. Do NOT overeat. Excessive weight makes people look older and correlates with dozens of illnesses. Typically I eat twice a day within a 6-hour window or once a day, no snacking. Eating 3+ times a day is just a (bad) habit.

4. EXERCISE. Moderate but regular exercise makes people look healthier and live longer. Personally, I don’t do much cardio (I’d rather walk/cycle/swim in the open air) and prefer moderate weights.

5. LIMIT stress. There are mental habits that help. It helps to believe that everything that happens is for the better. Stoic techniques such as negative visualisation and generally not giving a shit also work. Living close to nature makes all of the above easier.

6. Do NOT eat meat. Eating seafood and wild-caught fish is fine, but farmed red meat is something most people who look younger than their age avoid. I suspect the unhealthy nature of farmed meat has to do with the way livestock is raised and killed (growth hormones, fodder etc).

7. Live ALONE. Surprisingly, all the young-looking, middle-aged men I spoke with lived alone for most of their lives. It may be the result of their independence from the sleeping/eating/behavioral patterns of another person. Or it’s just correlation, and people who are independent from unhealthy societal norms are also independent in their personal lives. 

Interestingly, you can find scientific explanations for most of these points (even the last one is defensible, e.g. there are multiple studies showing that sleeping alone improves the quality of sleep). I’ve been following these rules for over 10 years, with "more sleep" being the most difficult due to the nature of my work. 

If you are twice as young as I am and looking for the key takeaway, here it is: NEVER DRINK ALCOHOL. Once you give up on alcohol, you’ll stop silencing your intuition, which will tell you what is good and what is bad for you. You will figure out everything you need to know by yourself and won’t depend on other people for advice.

**Comment by youtai2020** [comment]
卸载和注销微博、即刻、Twitter。

**Comment by youtai2020** [comment]
> 卸载和注销微博、即刻、Twitter。

bilibili 也注销了！

**Comment by youtai2020** [comment]
when you are tired, learn to rest not to learn to quit.

**Comment by youtai2020** [comment]
今天凌晨的苹果发布会：
1. 官网的流居然很卡，这也是第一会这么卡，我想已苹果公司的实力，正常的访问观众，应该不会至于吧；
2. 科技博主在进行直播的时候，都被停播了，不能出现转播画面，如果这是牵扯到侵权，能理解，但是好像应该不是这个样子的；

**Comment by youtai2020** [comment]
今天有一个大学的学生自杀了，自杀前还在微博上写了一些文字，痛心疾首，很难过的，也说不出来，就难过，无意去讽刺和说一些东西，真的难受坏了。

**Comment by youtai2020** [comment]
[老梁：人性与信仰之间的关系](https://www.youtube.com/watch?v=xHVgi2mWMeY)，老梁最后说了脏话，差点哭了，就是很难受，难受到难过，难道我正在这片土地就要带着一些别的东西嘛？

**Comment by youtai2020** [comment]
from kk.
> Being enthusiastic is worth 25 IQ points.

**Comment by youtai2020** [comment]
一周不能只是工作，除了工作还有其他很多东西的，人生不只是赚钱那么简单，给自己一个规定，每周的周末不做任何和工作有关的事情，洗衣服、看书、看电影、听音乐都可以，有时候加油站很重要。

**Comment by youtai2020** [comment]
三十岁那年，我想给自己的生日礼物是南京大学的研究生，并且再次重回南京，不再离开。

**Comment by youtai22** [comment]
找工作真的是会无尽的焦虑，同时深深怀疑自己的能力。

**Comment by youtai22** [comment]
还是自己太菜了，避免菜的唯一途径就是学习呀！好像很内卷了，但是自己确实很菜了！

**Comment by youtai22** [comment]
突然陷入了情绪的洼地，蜷缩在床上，想着 26 的这一切，一事无成，好丧啊，丧到不行。

**Comment by youtai22** [comment]
> 突然陷入了情绪的洼地，蜷缩在床上，想着 26 的这一切，一事无成，好丧啊，丧到不行。

干啥啥不行，想改变自己又屡次放弃，什么也没有，眼高手低，好像就放弃自己，没有个人能力却还喜欢吹牛逼。感觉对不起父母。这个世界上厉害的人太多了，我干什么都干不好，好难过。

**Comment by youtai22** [comment]
#面试

10.20 下午去了一家公司面试，涉及到的主要问题是离职的原因，因为我说的还是很想去大一点公司或者需要大一点平台，无奈对方是一个小的平台，甚至，嗯，业务驱动（赚钱驱动），面试的时候没有什么大问题，因为很害怕被技术，特别是很详细的技术点，不是不会而是很多东西知道个大概，不想像背题目一样。

**Comment by youtai22** [comment]
#面试

10.20 下午面试了第二家公司，一个做外贸生意的公司，也基本上算是拿到 offer 了，现在就是很尴尬，倒不是钱多钱少的问题，而是好像这份工作对我以后的工作发展没啥用，就很纠结。其实钱吧，还行，符合现在的情况，房子还快到期了，还是很头疼的，不过好歹手里有了一个 offer 还行吧。

**Comment by youtai22** [comment]
从开始找工作开始还是很慌的，面试两家后，越来越觉得基础很重要，非常重要了，希望后面的两年能打好基础，早日进大厂！

不管遇到什么样子的失败都不要气馁，生活就是这样子的。

**Comment by youtai22** [comment]
Todo：这次找工作可以好好总结一下，很多的技巧、准备，本来以为这次找工作算是辞职了准备的蛮好的，但是还是很有差距的，还是没有这个经验，我面试了现在有 3 家了，还有很多的技巧，这次经验一定要写出来的。

**Comment by youtai22** [comment]
希望明天面试能一切顺利！

**Comment by sunyunxian** [comment]
不知不觉到公司上班有一周了，说不出来的感受吧，还是很想念周末，觉得周末才是自己的，很多东西很微妙的。

**Comment by sunyunxian** [comment]
经历过这一次的恋爱，我想基本上可以说成熟了，甚至产生了一辈子不想结婚的念头，两个人能合适太重要了，希望能平稳的把这个不小心导致的后果能稳稳的度过，我也会重新开始自己的职业生涯！做爱的时候一定要小心，不要为了一时的舒服和冲动，克制很重要，而且如果不爱了，就要勇敢的表达出来，不要怕伤害，那样只会伤害的更深！

**Comment by sunyunxian** [comment]
听了会李志，真好 [2015 -北京看见演唱会](https://youtu.be/_r9w3hE0s0U)

**Comment by sunyunxian** [comment]
社交媒体 follow 不要超过 50 - 100 人，如果超过就要考虑进行筛减！同理 rss 订阅也是一样的。

**Comment by sunyunxian** [comment]
社交媒体 follow 不要超过 50 - 100 人，如果超过就要考虑进行筛减！同理 rss 订阅也是一样的。

**Comment by sunyunxian** [comment]
一个人使用飞书的体验应该也会很好吧！

**Comment by sunyunxian** [comment]
这一条就是从飞书发送的

**Comment by sunyunxian** [comment]
好像都快忘了还有这么一个树洞的地方

**Comment by sunyunxian** [comment]
单身快乐！单身真好！
